apiVersion: v1
kind: Service
metadata:
  name: grpcclient-nodeport-service
spec:
  type: NodePort
  selector:
    app: grpcclientapp
  ports:
    - name: grpcclientapp
      protocol: TCP
      port: 80
      targetPort: 80