apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcserverapp-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcserverapp
  template:
    metadata:
      labels:
        app: grpcserverapp
    spec:
      containers:
        - name: grpcserverapp
          image: kadirkdr/grpcserverapp:latest
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "400Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: grpcserverapp-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: grpcserverapp
  ports:
  - name: grpcserverapp
    protocol: TCP
    port: 80
    targetPort: 80
  - name: grpcserverappgrpc
    protocol: TCP
    port: 666
    targetPort: 666