apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcclientapp-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcclientapp
  template:
    metadata:
      labels:
        app: grpcclientapp
    spec:
      containers:
        - name: grpcclientapp
          image: kadirkdr/grpcclientapp:latest
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "400Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: grpcclientapp-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: grpcclientapp
  ports:
  - name: grpcclientapp
    protocol: TCP
    port: 80
    targetPort: 80
  - name: grpcclientappgrpc
    protocol: TCP
    port: 666
    targetPort: 666